version: '3'
services:
  mysql:
    image: 'mysql:8'
    ports:
      - '3306:3306'
  environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=hello7
    - MYSQL_USER=hello7user
    - MYSQL_PASSWORD=bk